const minimist = require('minimist');
const fs = require('fs');
const _ = require('lodash');

function isPrimitive(test) {
  return (test !== Object(test));
}


function serializeAllKeys(obj) {
  const res = [];

  function f(obj, arrPath) {
    if (!arrPath) {
      arrPath = [];
    }
    if (isPrimitive(obj)) {
      res.push(arrPath.join('.'));
    } else {
      for (key in obj) {
        const value = obj[key];
        f(value, arrPath.concat(key))
      }
    }
  }

  f(obj);
  return res;
}

let compare = function (leftObject, rightObject) {

  let result = {
    missingFromSecond: []
  };

  _.reduce(leftObject, function (result, value, key) {
    if (rightObject.hasOwnProperty(key)) {
      if (_.isEqual(value, rightObject[key])) {
        return result;
      } else {
        if (isPrimitive(leftObject[key]) || isPrimitive(rightObject[key])) {
          return result; // primitive type
        } else {
          let deeper = compare(leftObject[key], rightObject[key]);
          result.missingFromSecond = result.missingFromSecond.concat(_.map(deeper.missingFromSecond, (sub_path) => {
            return key + "." + sub_path;
          }));
          return result;
        }
      }
    } else {
      result.missingFromSecond.push(key);
      //need to list all its children
      // result.missingFromSecond = result.missingFromSecond.concat(serializeAllKeys(leftObject[key]));
      return result;
    }
  }, result);

  return result;
};

const argv = minimist(process.argv.slice(2));
let firstFileName = argv._[0];
let secondFileName = argv._[1];

if (!firstFileName || !secondFileName) {
  console.error("You need to provide two files for comparing?");
  process.exit(-1);
}

if (argv.help) {
  console.info(`
    Shows deep the difference between the two objects in json files 
    Usage: node compare_objects.js FILE1.json FILE2.json
    
    FILE1.json is the json file generated by the ngx-translate-extract tool 
    from the source code 
    FILE2.json is the json file generated from the csv file by csv2json-i18n tool 
    
    `);
  process.exit(-1);
}

const obj1 = JSON.parse(fs.readFileSync(firstFileName, 'utf8'));
const obj2 = JSON.parse(fs.readFileSync(secondFileName, 'utf8'));
console.log(compare(obj1, obj2).missingFromSecond.join('\n'));
