export enum RegistrationStep {
  SELECT_ROLE_STEP = <any>'SELECT_ROLE_STEP',
  JOBSEEKER_IDENTIFICATION_STEP = <any>'JOBSEEKER_IDENTIFICATION_STEP',
  COMPANY_IDENTIFICATION_STEP = <any>'COMPANY_IDENTIFICATION_STEP',
  COMPANY_REQUEST_ACCESS_STEP = <any>'COMPANY_REQUEST_ACCESS_STEP',
  PAV_IDENTIFICATION_STEP = <any>'PAV_IDENTIFICATION_STEP',
  PAV_REQUEST_ACCESS_STEP = <any>'PAV_REQUEST_ACCESS_STEP'
}
