export enum RegistrationStep {
  SELECT_ROLE_STEP = 'SELECT_ROLE_STEP',
  JOBSEEKER_IDENTIFICATION_STEP = 'JOBSEEKER_IDENTIFICATION_STEP',
  COMPANY_IDENTIFICATION_STEP = 'COMPANY_IDENTIFICATION_STEP',
  COMPANY_REQUEST_ACCESS_STEP = 'COMPANY_REQUEST_ACCESS_STEP',
  PAV_IDENTIFICATION_STEP = 'PAV_IDENTIFICATION_STEP',
  PAV_REQUEST_ACCESS_STEP = 'PAV_REQUEST_ACCESS_STEP'
}
